"""empty message

Revision ID: 282518e193fd
Revises: 3486df8a7a98
Create Date: 2014-03-03 21:14:56.178550

"""

# revision identifiers, used by Alembic.
revision = '282518e193fd'
down_revision = '3486df8a7a98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
