"""empty message

Revision ID: 3486df8a7a98
Revises: 81055d7ae1e
Create Date: 2014-03-03 21:13:44.365095

"""

# revision identifiers, used by Alembic.
revision = '3486df8a7a98'
down_revision = '81055d7ae1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'client_key',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.create_unique_constraint(None, 'event', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event')
    op.alter_column('client', 'client_key',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    ### end Alembic commands ###
