"""empty message

Revision ID: 37fe1af81d08
Revises: 8a9e62a1836
Create Date: 2014-02-18 23:49:28.344685

"""

# revision identifiers, used by Alembic.
revision = '37fe1af81d08'
down_revision = '8a9e62a1836'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pedo', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pedo')
    ### end Alembic commands ###
