"""empty message

Revision ID: 420b583836a0
Revises: 43af914ae99c
Create Date: 2014-02-21 00:35:33.207711

"""

# revision identifiers, used by Alembic.
revision = '420b583836a0'
down_revision = '43af914ae99c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('iso_name', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('DDI',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['country_code'], ['country.code'], ),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('number')
    )
    op.add_column(u'action_config', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column(u'client', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.drop_column(u'user', 'active')
    op.drop_column(u'client', 'active')
    op.drop_column(u'action_config', 'client_id')
    op.drop_table('DDI')
    op.drop_table('country')
    ### end Alembic commands ###
