"""empty message

Revision ID: 43af914ae99c
Revises: None
Create Date: 2014-02-20 00:03:32.692856

"""

# revision identifiers, used by Alembic.
revision = '43af914ae99c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_config',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('step', sa.SmallInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', 'tag', 'step'),
    sa.UniqueConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('client_key', sa.String(length=254), nullable=False),
    sa.Column('credits', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'client_key'),
    sa.UniqueConstraint('client_key'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_client_name', 'client', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_client_name', table_name='client')
    op.drop_table('client')
    op.drop_table('action_config')
    ### end Alembic commands ###
