"""empty message

Revision ID: 81055d7ae1e
Revises: None
Create Date: 2014-03-03 21:11:26.964593

"""

# revision identifiers, used by Alembic.
revision = '81055d7ae1e'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('step', sa.SmallInteger(), nullable=True),
    sa.Column('ip_addr', postgresql.INET(), nullable=True),
    sa.Column('reception_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash', sa.String(length=256), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_event_hash', 'event', ['hash'], unique=False)
    op.alter_column(u'client', 'client_key',
               existing_type=sa.VARCHAR(length=254)
               )
    op.create_index('ix_client_client_key', 'client', ['client_key'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_client_key', table_name='client')
    op.alter_column(u'client', 'client_key',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.drop_index('ix_event_hash', table_name='event')
    op.drop_table('event')
    ### end Alembic commands ###
