"""empty message

Revision ID: 97e7ae3bc98
Revises: 37fe1af81d08
Create Date: 2014-02-18 23:50:45.348413

"""

# revision identifiers, used by Alembic.
revision = '97e7ae3bc98'
down_revision = '37fe1af81d08'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pedo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pedo', mysql.VARCHAR(length=128), nullable=True))
    ### end Alembic commands ###
