"""empty message

Revision ID: a5134e980ba
Revises: 420b583836a0
Create Date: 2014-02-26 20:18:33.734340

"""

# revision identifiers, used by Alembic.
revision = 'a5134e980ba'
down_revision = '420b583836a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('simple_email_params',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('retries', sa.SmallInteger(), nullable=True),
    sa.Column('language', sa.Integer(), nullable=True),
    sa.Column('pin', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('annouce_call_params',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ddi', sa.BigInteger(), nullable=True),
    sa.Column('cli', sa.Integer(), nullable=True),
    sa.Column('retries', sa.SmallInteger(), nullable=True),
    sa.Column('language', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ddi'], ['DDI.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('simple_call_params',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ddi', sa.BigInteger(), nullable=True),
    sa.Column('cli', sa.Integer(), nullable=True),
    sa.Column('retries', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ddi'], ['DDI.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('simple_sms_params',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ddi', sa.BigInteger(), nullable=True),
    sa.Column('cli', sa.Integer(), nullable=True),
    sa.Column('retries', sa.SmallInteger(), nullable=True),
    sa.Column('pin', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ddi'], ['DDI.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('acknowledged_call_params',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ddi', sa.BigInteger(), nullable=True),
    sa.Column('cli', sa.Integer(), nullable=True),
    sa.Column('retries', sa.SmallInteger(), nullable=True),
    sa.Column('language', sa.Integer(), nullable=True),
    sa.Column('pin', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ddi'], ['DDI.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'DDI', ['number'])
    op.add_column(u'action_config', sa.Column('action_type_id', sa.Integer(), nullable=True))
    op.drop_column(u'action_config', 'action_type')
    op.drop_column(u'user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    op.add_column(u'action_config', sa.Column('action_type', sa.VARCHAR(length=128), nullable=True))
    op.drop_column(u'action_config', 'action_type_id')
    op.drop_constraint(None, 'DDI')
    op.drop_table('acknowledged_call_params')
    op.drop_table('simple_sms_params')
    op.drop_table('simple_call_params')
    op.drop_table('annouce_call_params')
    op.drop_table('simple_email_params')
    op.drop_table('action_type')
    ### end Alembic commands ###
